"""model updated for platform

Revision ID: 1929ddbee064
Revises: 4f4fa56b8c00
Create Date: 2023-10-15 20:32:56.736181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1929ddbee064'
down_revision = '4f4fa56b8c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'platform')
    # ### end Alembic commands ###
