"""reason added

Revision ID: acbe4cf97040
Revises: 1d3e678aa6a7
Create Date: 2023-10-09 17:47:21.366589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbe4cf97040'
down_revision = '1d3e678aa6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'reason')
    # ### end Alembic commands ###
