"""username added

Revision ID: 23eed31ea938
Revises: 2b65939741c6
Create Date: 2023-11-21 21:18:45.151757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eed31ea938'
down_revision = '2b65939741c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'username')
    # ### end Alembic commands ###
