"""auth added

Revision ID: 2b65939741c6
Revises: c05c2647ddcb
Create Date: 2023-11-18 13:57:19.393960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b65939741c6'
down_revision = 'c05c2647ddcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authorised', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authorised')
    # ### end Alembic commands ###
