"""platform url key  added

Revision ID: 30dc6f932d06
Revises: ad7799dc4976
Create Date: 2023-12-09 03:23:03.143611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dc6f932d06'
down_revision = 'ad7799dc4976'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('url_key', sa.String(), nullable=True))
    op.execute("UPDATE platform SET url_key = ''")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'url_key')
    # ### end Alembic commands ###
