"""distributor_added

Revision ID: 4e1e23d3f7c7
Revises: 31475a7f565a
Create Date: 2023-12-26 23:54:38.576727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1e23d3f7c7'
down_revision = '31475a7f565a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('is_email_authorised', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_email'), 'distributor', ['email'], unique=True)
    op.create_index(op.f('ix_distributor_unique_id'), 'distributor', ['unique_id'], unique=False)
    op.create_index(op.f('ix_distributor_username'), 'distributor', ['username'], unique=True)
    op.create_table('distributor_accounts',
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_account_email', table_name='account')
    op.drop_column('account', 'name')
    op.drop_column('account', 'is_email_authorised')
    op.drop_column('account', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('account', sa.Column('is_email_authorised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_account_email', 'account', ['email'], unique=False)
    op.drop_table('distributor_accounts')
    op.drop_index(op.f('ix_distributor_username'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_unique_id'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_email'), table_name='distributor')
    op.drop_table('distributor')
    # ### end Alembic commands ###
