"""amount added

Revision ID: 6a725d2d4adc
Revises: cb50095ea695
Create Date: 2023-11-30 23:48:33.526875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a725d2d4adc'
down_revision = 'cb50095ea695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('amount', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'amount')
    # ### end Alembic commands ###
