"""auth added

Revision ID: ad7799dc4976
Revises: 6a725d2d4adc
Create Date: 2023-12-09 02:07:18.680163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7799dc4976'
down_revision = '6a725d2d4adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_email_authorised', sa.Boolean(), nullable=True))
    op.execute('UPDATE account SET is_email_authorised = true')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_email_authorised')
    # ### end Alembic commands ###
