"""multi_user support

Revision ID: c05c2647ddcb
Revises: 1929ddbee064
Create Date: 2023-11-18 00:28:38.068242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05c2647ddcb'
down_revision = '1929ddbee064'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('primary_user_id', sa.Integer(), nullable=True),
    sa.Column('secondary_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('primary_email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('unique_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_primary_email'), 'user', ['primary_email'], unique=False)
    op.create_index(op.f('ix_user_unique_id'), 'user', ['unique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_unique_id'), table_name='user')
    op.drop_index(op.f('ix_user_primary_email'), table_name='user')
    op.drop_column('user', 'unique_id')
    op.drop_column('user', 'primary_email')
    op.drop_column('user', 'is_primary')
    op.drop_table('user_account')
    # ### end Alembic commands ###
