"""registration added fix

Revision ID: cb50095ea695
Revises: e9cd150cfff3
Create Date: 2023-11-29 19:19:34.581952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb50095ea695'
down_revision = 'e9cd150cfff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_user_account_id_fkey', 'account_user', type_='foreignkey')
    op.create_foreign_key(None, 'account_user', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_user', type_='foreignkey')
    op.create_foreign_key('account_user_account_id_fkey', 'account_user', 'user', ['account_id'], ['id'])
    # ### end Alembic commands ###
