"""registration added

Revision ID: e9cd150cfff3
Revises: 23eed31ea938
Create Date: 2023-11-29 02:12:28.667144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9cd150cfff3'
down_revision = '23eed31ea938'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_unique_id'), 'account', ['unique_id'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('account_user',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_account')
    op.drop_index('ix_user_primary_email', table_name='user')
    op.drop_column('user', 'primary_email')
    op.drop_column('user', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('primary_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_primary_email', 'user', ['primary_email'], unique=False)
    op.create_table('user_account',
    sa.Column('primary_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secondary_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['primary_user_id'], ['user.id'], name='user_account_primary_user_id_fkey'),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.id'], name='user_account_secondary_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_account_pkey')
    )
    op.drop_table('account_user')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_unique_id'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
